version: "3.8"
services:
  dev:
    image: guest-passes-frontend
    build: .
    command: ["yarn", "start"]
    ports:
      - "3000:3000"
    depends_on: 
        - backend
        - db

  backend:
    image: guest-passes-backend
    build: .
    command: ["yarn", "start-dev-backend"]
    ports:
      - "5000:5000"
    depends_on: 
      - db
    volumes:
      - .:/app
      - ./migrations:/app/migrations
      - node_modules:/app/node_modules

  db:
    image: mysql:5.7
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: test
    restart: always 
    cap_add:
      - SYS_NICE

volumes:
  node_modules: