version: "3.8"

x-default-volumes: &default-volumes
  volumes:
    - .:/app
    - ./migrations:/app/migrations
    - node_modules:/app/node_modules

x-build: &x-build
  image: guest-passes
  build:
    context: .
    cache_from:
      - guest-passes
      - "quay.io/nyulibraries/guest-passes"
      - "quay.io/nyulibraries/guest-passes:${BRANCH_NO_SLASH}"

x-build-e2e: &x-build-e2e
  image: guest-passes-e2e
  build:
    context: ./cypress
      #dockerfile: ./cypress/Dockerfile
    cache_from:
      - guest-passes-e2e
      - "quay.io/nyulibraries/guest-passes-e2e"
      - "quay.io/nyulibraries/guest-passes-e2e:${BRANCH_NO_SLASH}"

services:
  backend:
    <<: *x-build
    command: ["/tmp/wait-for", "db:3306", "--", "yarn", "start-dev-backend"]
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
    depends_on:
      - db
      #<<: *default-volumes

  curl-dev:
    image: appropriate/curl
    command: [ "dev:3000" ]
    depends_on:
      - dev

  db:
    image: mysql:5.7
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: test

  dev:
    <<: *x-build
    command: ["/tmp/wait-for", "backend:5000", "-t 60", "--", "yarn", "start"]
    ports:
      - "3000:3000"
    depends_on:
      - backend
      #<<: *default-volumes

  dev-e2e:
    <<: *x-build
    command: ["/tmp/wait-for", "backend:5000", "-t 60", "--", "yarn", "start"]
    ports:
      - "4000:4000"
    depends_on:
      - backend
    environment:
      PORT: 4000
      REACT_APP_BACKEND_FULL_HOST: http://backend:5000
      #<<: *default-volumes

  e2e:
    <<: *x-build-e2e
    #command: ["yarn", "cypress", "run", "--headless"]
    depends_on:
      - dev-e2e
      - backend
    environment:
      DOMAIN: http://dev-e2e:4000/
      NODE_ENV: test
      CYPRESS_BASE_URL: http://dev-e2e:4000/
    ipc: host

  setup_tests:
    <<: *x-build
    command:
      - /bin/sh
      - -c
      - |
        /tmp/wait-for db:3306 -t 60 -- 
        yarn sequelize db:create &&
        yarn sequelize db:migrate
    environment:
      NODE_ENV: test
    depends_on:
      - db

  test:
    <<: *x-build
    command:
      - /bin/sh
      - -c
      - |
        /tmp/wait-for db:3306 -- sleep 5 && yarn test
    depends_on:
      - setup_tests
    environment:
      NODE_ENV: test
    # <<: *default-volumes

volumes:
  node_modules:
