version: "3.8"

x-default-volumes: &default-volumes
  volumes:
    - .:/app
    - ./migrations:/app/migrations
    - node_modules:/app/node_modules

services:
  dev:
    image: guest-passes
    build: .
    command: ["/tmp/wait-for", "backend:5000", "-t 60", "--", "yarn", "start"]
    ports:
      - "3000:3000"
    depends_on:
      - backend
        #<<: *default-volumes

  backend:
    image: guest-passes
    build: .
    command: ["/tmp/wait-for", "db:3306", "--", "yarn", "start-dev-backend"]
    ports:
      - "5000:5000"
    depends_on:
      - db
        #<<: *default-volumes

  db:
    image: mysql:5.7
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: test
    # restart: always
    # cap_add:
    #   - SYS_NICE

  test:
    image: guest-passes
    build: .
    command:
      ["/tmp/wait-for", "db:3306", "--", "npm", "test", "--", "--watchAll=false"]
    depends_on:
      - db

  curl-dev:
    image: appropriate/curl
    command: ["dev:3000"]
    depends_on:
      - dev

volumes:
  node_modules:
