version: "3.8"
services:
  dev:
    build: .
    ports:
      - "3000:3000"

  db:
    image: mysql
    # image: mysql:5.7
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: test
    restart: always 
    cap_add:
      - SYS_NICE

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.node
    ports:
      - "4000:5000"
    depends_on: 
      - db
    volumes:
      - .:/app
      - ./migrations:/app/migrations

