version: 2.1

# Environments
dev: &dev 'DEV'
prod: &prod 'PROD'

auth_quay: &auth_quay
  run:
    name: Authenticate Quay
    command: |
      docker login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io

copy_build: &copy_build
  run:
    name: Copy build
    command: |
      docker cp $(docker ps -a -q --filter name=compile-frontend-prod):/app/build ./

docker-defaults: &docker-defaults
  docker:
    - image: quay.io/nyulibraries/circleci_docker:19.03.13-dc-1.27.4-0
  working_directory: ~/app

environment-parameter: &environment-parameter
  environment:
    type: enum
    enum: [ *dev, *prod]

hermes_deploy: &hermes_deploy
  run:
    name: Deploy via Hermes
    command: |
      export TAG=${CIRCLE_BRANCH//\//_}-${CIRCLE_SHA1}
      docker run -e HERMES_HOST -e HERMES_SECRET quay.io/nyulibraries/hermesclient:master setImage -deployment=guestpasses-nodejs -tag=$TAG
      docker run -e HERMES_HOST -e HERMES_SECRET quay.io/nyulibraries/hermesclient:master setImage -deployment=guestpasses-react-nginx -tag=$TAG
      docker run -e HERMES_HOST -e HERMES_SECRET -e HERMES_WAIT_PAUSE_MIN=1s -e HERMES_WAIT_PAUSE_MAX=2s quay.io/nyulibraries/hermesclient:chore_configure_pause rolloutStatus -deployment=guestpasses-nodejs
      docker run -e HERMES_HOST -e HERMES_SECRET -e HERMES_WAIT_PAUSE_MIN=1s -e HERMES_WAIT_PAUSE_MAX=2s quay.io/nyulibraries/hermesclient:chore_configure_pause rolloutStatus -deployment=guestpasses-react-nginx

test_build: &test_build
  run:
    name: Test that correct files were built
    command: |
      test -e build/index.html
      test -e build/asset-manifest.json
      test -e build/static/css/main.*.css
      test -e build/static/css/main.*.map
      test -e build/static/js/main.*.js
      test -e build/static/js/main.*.map

commands:
  aws-env:
    description: Set AWS environment variables
    parameters:
      <<: *environment-parameter
    steps:
      -   run:
            name: Export AWS env vars
            command: |
              # AWS IAM user web-s3-guestpasses-website
              echo 'export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_<< parameters.environment >>}' >> $BASH_ENV
              echo 'export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_<< parameters.environment >>}' >> $BASH_ENV

  deploy-application:
    description: Build application, test the build, deploy to S3, and export Hermes env vars
    parameters:
        <<: *environment-parameter
    steps:
      - checkout
      - setup_remote_docker
      - <<: *auth_quay
      - run:
          name: Build << parameters.environment >> frontend
          command: |
            export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
            docker-compose run compile-frontend-prod
      - *copy_build
      - *test_build
      - aws-env:
          environment: << parameters.environment >>
      - s3-sync:
          environment: << parameters.environment >>
      - export-hermes-env-vars:
          environment: << parameters.environment >>
      - <<: *hermes_deploy

  export-hermes-env-vars:
    description: Export Hermes env vars
    parameters:
        <<: *environment-parameter
    steps:
      - when:
          condition:
            equal: [ *dev, << parameters.environment >> ]
          steps:
            - run:
                name: Export Hermes env vars
                command: |
                  echo 'export HERMES_HOST=https://hermes-dev.library.nyu.edu' >> $BASH_ENV
                  echo 'export HERMES_SECRET=$HERMES_SECRET_DEV' >> $BASH_ENV
      - when:
          condition:
            equal: [ *prod, << parameters.environment >> ]
          steps:
            - run:
                name: Export Hermes env vars
                command: |
                  echo 'export HERMES_HOST=https://hermes.library.nyu.edu' >> $BASH_ENV
                  echo 'export HERMES_SECRET=$HERMES_SECRET_PROD' >> $BASH_ENV

  s3-sync:
    description: Sync with S3 bucket
    parameters:
        <<: *environment-parameter
    steps:
      - aws-s3/sync:
          from: build
          to: '${S3_URI_<< parameters.environment >>}'
          arguments: |
            --delete

orbs:
    aws-s3: circleci/aws-s3@3.0.0

jobs:
  build-test:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Docker Pull
          command: |
            docker-compose pull db
            docker pull quay.io/nyulibraries/guest-passes:${CIRCLE_BRANCH//\//_} || docker pull quay.io/nyulibraries/guest-passes:latest
            docker pull quay.io/nyulibraries/guest-passes-e2e:${CIRCLE_BRANCH//\//_} || docker pull quay.io/nyulibraries/guest-passes-e2e:latest
      - run:
          name: Build
          command: |
            export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
            docker-compose build
      - run:
          name: Unit Tests
          command: |
            docker-compose run test
      - run:
          name: Integration Tests
          command: |
            docker-compose run e2e
            #- run:
            #    name: Test if dev starts properly
            #    command: |
            #      docker-compose up -d dev
            #      timeout 1m sh -c 'until docker-compose run curl-dev; do sleep 5; done'
            #      script/check_dev.sh
      - <<: *auth_quay
      - run:
          name: Push image
          command: |
            export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
            docker tag guest-passes quay.io/nyulibraries/guest-passes:${BRANCH_NO_SLASH}
            docker tag guest-passes quay.io/nyulibraries/guest-passes:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}
            docker tag guest-passes quay.io/nyulibraries/guest-passes:latest
            docker tag guest-passes-e2e quay.io/nyulibraries/guest-passes-e2e:${BRANCH_NO_SLASH}
            docker tag guest-passes-e2e quay.io/nyulibraries/guest-passes-e2e:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}
            docker tag guest-passes-e2e quay.io/nyulibraries/guest-passes-e2e:latest
            docker push quay.io/nyulibraries/guest-passes:${BRANCH_NO_SLASH}
            docker push quay.io/nyulibraries/guest-passes:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}
            docker push quay.io/nyulibraries/guest-passes:latest
            docker push quay.io/nyulibraries/guest-passes-e2e:${BRANCH_NO_SLASH}
            docker push quay.io/nyulibraries/guest-passes-e2e:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}
            docker push quay.io/nyulibraries/guest-passes-e2e:latest

  deploy-dev:
    <<: *docker-defaults
    steps:
      - deploy-application:
          environment: *dev

  deploy-prod:
    <<: *docker-defaults
    steps:
      - deploy-application:
          environment: *prod

workflows:
  build-test-and-deploy:
    jobs:
      - build-test
      - deploy-dev:
          requires:
              - build-test
          filters:
            branches:
              ignore: main
      - deploy-prod:
          requires:
              - build-test
          filters:
            branches:
              only: main
