docker-defaults: &docker-defaults
  docker:
    - image: quay.io/nyulibraries/circleci_docker:19.03.13-dc-1.27.4-0
  working_directory: ~/app

auth_quay: &auth_quay
  run:
    name: Authenticate Quay
    command: |
      docker login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io
      
hermes_deploy: &hermes_deploy
  run:
    name: Deploy via Hermes
    command: |
      export TAG=${CIRCLE_BRANCH//\//_}-${CIRCLE_SHA1}
      docker run -e HERMES_HOST -e HERMES_SECRET quay.io/nyulibraries/hermesclient:master setImage -deployment=guestpasses-nodejs -tag=$TAG
      docker run -e HERMES_HOST -e HERMES_SECRET quay.io/nyulibraries/hermesclient:master setImage -deployment=guestpasses-react-nginx -tag=$TAG
      docker run -e HERMES_HOST -e HERMES_SECRET -e HERMES_WAIT_PAUSE_MIN=1s -e HERMES_WAIT_PAUSE_MAX=2s quay.io/nyulibraries/hermesclient:chore_configure_pause rolloutStatus -deployment=guestpasses-nodejs
      docker run -e HERMES_HOST -e HERMES_SECRET -e HERMES_WAIT_PAUSE_MIN=1s -e HERMES_WAIT_PAUSE_MAX=2s quay.io/nyulibraries/hermesclient:chore_configure_pause rolloutStatus -deployment=guestpasses-react-nginx

version: 2
jobs:
  build-test:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Docker Pull
          command: |
            docker-compose pull db
            docker pull quay.io/nyulibraries/guest-passes:${CIRCLE_BRANCH//\//_} || docker pull quay.io/nyulibraries/guest-passes:latest
            docker pull quay.io/nyulibraries/guest-passes-e2e:${CIRCLE_BRANCH//\//_} || docker pull quay.io/nyulibraries/guest-passes-e2e:latest
      - run:
          name: Build
          command: |
            export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
            docker-compose build
      - run:
          name: Unit Tests
          command: |
            docker-compose run test
      - run:
          name: Integration Tests
          command: |
            docker-compose run e2e
            #- run:
            #    name: Test if dev starts properly
            #    command: |
            #      docker-compose up -d dev 
            #      timeout 1m sh -c 'until docker-compose run curl-dev; do sleep 5; done'
            #      script/check_dev.sh
      - <<: *auth_quay
      - run:
          name: Push image
          command: |
            export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
            docker tag guest-passes quay.io/nyulibraries/guest-passes:${BRANCH_NO_SLASH}
            docker tag guest-passes quay.io/nyulibraries/guest-passes:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}
            docker tag guest-passes quay.io/nyulibraries/guest-passes:latest
            docker tag guest-passes-e2e quay.io/nyulibraries/guest-passes-e2e:${BRANCH_NO_SLASH}
            docker tag guest-passes-e2e quay.io/nyulibraries/guest-passes-e2e:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}
            docker tag guest-passes-e2e quay.io/nyulibraries/guest-passes-e2e:latest
            docker push quay.io/nyulibraries/guest-passes:${BRANCH_NO_SLASH}
            docker push quay.io/nyulibraries/guest-passes:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}
            docker push quay.io/nyulibraries/guest-passes:latest
            docker push quay.io/nyulibraries/guest-passes-e2e:${BRANCH_NO_SLASH}
            docker push quay.io/nyulibraries/guest-passes-e2e:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}
            docker push quay.io/nyulibraries/guest-passes-e2e:latest


  deploy-dev:
    <<: *docker-defaults
    steps:
      - setup_remote_docker
      - <<: *auth_quay
      - run:
          name: Export Hermes Dev env vars
          command: |
            echo 'export HERMES_HOST=https://hermes-dev.library.nyu.edu' >> $BASH_ENV
            echo 'export HERMES_SECRET=$HERMES_SECRET_DEV' >> $BASH_ENV
      - <<: *hermes_deploy

  deploy-prod:
    <<: *docker-defaults
    steps:
      - setup_remote_docker
      - <<: *auth_quay
      - run:
          name: Export Hermes Prod env vars
          command: |
            echo 'export HERMES_HOST=https://hermes.library.nyu.edu' >> $BASH_ENV
            echo 'export HERMES_SECRET=$HERMES_SECRET_PROD' >> $BASH_ENV
      - <<: *hermes_deploy

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build-test
      - deploy-dev:
          requires:
              - build-test
          filters:
            branches:
              ignore: main
      - deploy-prod:
          requires:
              - build-test
          filters:
            branches:
              only: main
