version: 2.1
auth_quay: &auth_quay
  run:
    name: Authenticate Quay
    command: |
      docker login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io

aws_env: &aws_env
  run:
    name: Export AWS env vars
    command: |
      # AWS IAM user web-s3-guestpasses-website 
      echo 'export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}' >> $BASH_ENV
      echo 'export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}' >> $BASH_ENV

copy_build: &copy_build
  run:
    name: Copy build
    command: |
      docker cp $(docker ps -a -q --filter name=compile-frontend-prod):/app/build ./

docker-defaults: &docker-defaults
  docker:
    - image: quay.io/nyulibraries/circleci_docker:19.03.13-dc-1.27.4-0
  working_directory: ~/app

hermes_deploy: &hermes_deploy
  run:
    name: Deploy via Hermes
    command: |
      export TAG=${CIRCLE_BRANCH//\//_}-${CIRCLE_SHA1}
      docker run -e HERMES_HOST -e HERMES_SECRET quay.io/nyulibraries/hermesclient:master setImage -deployment=guestpasses-nodejs -tag=$TAG
      docker run -e HERMES_HOST -e HERMES_SECRET quay.io/nyulibraries/hermesclient:master setImage -deployment=guestpasses-react-nginx -tag=$TAG
      docker run -e HERMES_HOST -e HERMES_SECRET -e HERMES_WAIT_PAUSE_MIN=1s -e HERMES_WAIT_PAUSE_MAX=2s quay.io/nyulibraries/hermesclient:chore_configure_pause rolloutStatus -deployment=guestpasses-nodejs
      docker run -e HERMES_HOST -e HERMES_SECRET -e HERMES_WAIT_PAUSE_MIN=1s -e HERMES_WAIT_PAUSE_MAX=2s quay.io/nyulibraries/hermesclient:chore_configure_pause rolloutStatus -deployment=guestpasses-react-nginx

s3_deploy: &s3_deploy
  aws-s3/sync:
    from: build
    to: '${S3_URI_DEV}'
    arguments: |
      --delete

test_build: &test_build
  run:
    name: Test that correct files were built
    command: |
      test -e build/index.html
      test -e build/asset-manifest.json
      test -e build/static/css/main.*.css
      test -e build/static/css/main.*.map
      test -e build/static/js/main.*.js
      test -e build/static/js/main.*.map

orbs:
    aws-s3: circleci/aws-s3@3.0.0
jobs:
  build-test:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Docker Pull
          command: |
            docker-compose pull db
            docker pull quay.io/nyulibraries/guest-passes:${CIRCLE_BRANCH//\//_} || docker pull quay.io/nyulibraries/guest-passes:latest
            docker pull quay.io/nyulibraries/guest-passes-e2e:${CIRCLE_BRANCH//\//_} || docker pull quay.io/nyulibraries/guest-passes-e2e:latest
      - run:
          name: Build
          command: |
            export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
            docker-compose build
      - run:
          name: Unit Tests
          command: |
            docker-compose run test
      - run:
          name: Integration Tests
          command: |
            docker-compose run e2e
            #- run:
            #    name: Test if dev starts properly
            #    command: |
            #      docker-compose up -d dev 
            #      timeout 1m sh -c 'until docker-compose run curl-dev; do sleep 5; done'
            #      script/check_dev.sh
      - <<: *auth_quay
      - run:
          name: Push image
          command: |
            export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
            docker tag guest-passes quay.io/nyulibraries/guest-passes:${BRANCH_NO_SLASH}
            docker tag guest-passes quay.io/nyulibraries/guest-passes:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}
            docker tag guest-passes quay.io/nyulibraries/guest-passes:latest
            docker tag guest-passes-e2e quay.io/nyulibraries/guest-passes-e2e:${BRANCH_NO_SLASH}
            docker tag guest-passes-e2e quay.io/nyulibraries/guest-passes-e2e:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}
            docker tag guest-passes-e2e quay.io/nyulibraries/guest-passes-e2e:latest
            docker push quay.io/nyulibraries/guest-passes:${BRANCH_NO_SLASH}
            docker push quay.io/nyulibraries/guest-passes:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}
            docker push quay.io/nyulibraries/guest-passes:latest
            docker push quay.io/nyulibraries/guest-passes-e2e:${BRANCH_NO_SLASH}
            docker push quay.io/nyulibraries/guest-passes-e2e:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}
            docker push quay.io/nyulibraries/guest-passes-e2e:latest

  deploy-dev:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - <<: *auth_quay
      - run:
          name: Build prod frontend
          command: |
            export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
            docker-compose run compile-frontend-prod
      - *copy_build
      - *test_build
      - *aws_env
      - *s3_deploy
      - run:
          name: Export Hermes Dev env vars
          command: |
            echo 'export HERMES_HOST=https://hermes-dev.library.nyu.edu' >> $BASH_ENV
            echo 'export HERMES_SECRET=$HERMES_SECRET_DEV' >> $BASH_ENV
      - <<: *hermes_deploy

  deploy-prod:
    <<: *docker-defaults
    steps:
      - setup_remote_docker
      - <<: *auth_quay
      - run:
          name: Export Hermes Prod env vars
          command: |
            echo 'export HERMES_HOST=https://hermes.library.nyu.edu' >> $BASH_ENV
            echo 'export HERMES_SECRET=$HERMES_SECRET_PROD' >> $BASH_ENV
      - <<: *hermes_deploy

workflows:
  build-test-and-deploy:
    jobs:
      - build-test
      - deploy-dev:
          requires:
              - build-test
          filters:
            branches:
              ignore: main
      - deploy-prod:
          requires:
              - build-test
          filters:
            branches:
              only: main
