export const statusList = [
  "",
  "Day Pass (Forgotten NYU ID)",
  "Day Pass (Forgotten NYU Friends ID)",
  "Day Pass (NYU ID not swiping)",
  "One Day [Guest of NYU Cardholder]",
  "One day: Visitor",
  "One Day: Guest Admission",
  "1-Time Only Alumni Visit",
  "One day: Bobst 3 Visit Card",
  "One day: Bobst 10 Visit Card",
  "One day: Visiting Faculty",
  "One day: Foreign student",
  "One Day: Admissions Tour Guest",
  "One day: Acceptance Letter",
  "Sponsored Access",
  "Sponsored Borrower",
  "Extended pass",
  "Faculty Resource Network",
  "Borrower: MaRLI [NYPL]",
  "Borrower: MaRLI [Col. PhD]",
  "Borrower: MaRLI [Col. Fac.]",
  "Borrower: New Museum",
  "Borrower: NYHS",
  "Borrower: Palmer School",
  "3-Day Pass (New School ID not swiping)",
  "[SH]Binghamton Univ.",
  "[SH]Boston College",
  "[SH]Boston Univ.",
  "[SH]Brown Univ.",
  "[SH]Carnegie Mellon Univ.",
  "[SH]Univ. of Chicago",
  "Columbia University",
  "[SH]Cornell Univ.",
  "Harvard",
  "[SH]Univ. of Michigan",
  "Mount Sinai Med. Center",
  "[SH]Univ. of Penn.",
  "[SH]Penn. State Univ.",
  "[SH]Princeton Univ.",
  "[SH]Rutgers Univ.",
  "[SH]Stony Brook Univ.",
  "[SH]Yale Univ.",
  "Friends of Bobst (Collector)",
  "Friends of Bobst (Reader)",
  "Friends of Bobst (Borrower)",
  "Sothebys Friends of Bobst",
  "Bobst Student Worker",
  "Dibner Student Worker",
];

export const restrictionList = [
  "",
  "Gen. Coll. + AFC",
  "General Collection (no AFC)",
  "U.S./U.N. Docs (Present to 5th fl. Lib.)",
  "Special Collections: Fales/Tam/Wag/University Archives",
  "Visual History Archives",
  "NYU Dissertations (Title or Author)",
  "METRO (specify in this field)",
];
